const $=s=>document.querySelector(s), $$=s=>document.querySelectorAll(s);
const state={lang:localStorage.getItem('qaraqalpagim-lang')||'kaa',cat:'all'};
const translations={
 kaa:{'nav.menu':'Mәзір','nav.about':'Біз туралы','nav.contacts':'Байланыс','nav.reserve':'Үстел броньдау','hero.line1':'Тамақ. Дәстүр.','hero.line2':'Үйдегідей жылу.','hero.desc':'Нукус төріндегі ұлттық дастархан: таныс дәм, үлкен порциялар және үйдегі көңіл-күй.','hero.open':'Мәзірді ашу','hero.more':'Біз туралы','hero.note':'Күн сайын · 10:00 — 23:00','about.tag':'БІЗ ТУРАЛЫ','about.title':'Бір дастархан,<br>бір үлкен үй.','about.desc':'Қарақалпағымда ұлттық тағамдар заманауи, ыңғайлы форматта беріледі. Менюдегі атаулар мен бағалар — сіз жіберген түпнұсқа мәзірден алынған. Сайт тек таңдауды жеңілдетеді.','menu.tag':'МӘЗІР · MENU','menu.title':'Дәмдісін таңдаңыз.','menu.desc':'TopStop-тағыдай түсінікті карточкалар: тағам суреті, атауы және мәзірдегі бағасы бір жерде.','menu.search':'Тағам іздеу…','story.title':'Қызмет көрсету ақысы','story.desc':'Түпнұсқа мәзірде көрсетілгендей, қызмет көрсету ақысы 10%.','contact.tag':'БАЙЛАНЫС','contact.title':'Қонақ болыңыз.<br>Дастархан дайын.','contact.hours':'Күн сайын · 10:00 — 23:00','reserve.tag':'БРОНЬ','reserve.title':'Үстел броньдау','reserve.name':'Атыңыз','reserve.phone':'Телефон','reserve.guests':'Қонақ саны','reserve.send':'Өтінім жіберу','all':'Барлығы','searchNone':'Ештеңе табылмады'},
 ru:{'nav.menu':'Меню','nav.about':'О нас','nav.contacts':'Контакты','nav.reserve':'Забронировать','hero.line1':'Вкус. Традиция.','hero.line2':'Тепло как дома.','hero.desc':'Национальный дастархан в самом сердце Нукуса: знакомые вкусы, большие порции и домашняя атмосфера.','hero.open':'Открыть меню','hero.more':'О нас','hero.note':'Ежедневно · 10:00 — 23:00','about.tag':'О РЕСТОРАНЕ','about.title':'Один дастархан,<br>один большой дом.','about.desc':'В Қарақалпағым национальные блюда подаются в удобном современном формате. Названия и цены в меню взяты из предоставленного оригинального меню.','menu.tag':'МЕНЮ · MENU','menu.title':'Выбирайте вкусное.','menu.desc':'Как в TopStop: отдельные карточки с фото, названием и ценой из оригинального меню.','menu.search':'Поиск блюда…','story.title':'Сервисный сбор','story.desc':'Как указано в оригинальном меню, сервисный сбор составляет 10%.','contact.tag':'КОНТАКТЫ','contact.title':'Будем рады.<br>Дастархан готов.','contact.hours':'Ежедневно · 10:00 — 23:00','reserve.tag':'БРОНЬ','reserve.title':'Забронировать столик','reserve.name':'Ваше имя','reserve.phone':'Телефон','reserve.guests':'Количество гостей','reserve.send':'Отправить заявку','all':'Все','searchNone':'Ничего не найдено'},
 en:{'nav.menu':'Menu','nav.about':'About','nav.contacts':'Contacts','nav.reserve':'Reserve','hero.line1':'Taste. Tradition.','hero.line2':'Warm as home.','hero.desc':'A national table in the heart of Nukus: familiar flavors, generous portions and a welcoming atmosphere.','hero.open':'Open menu','hero.more':'About us','hero.note':'Every day · 10:00 — 23:00','about.tag':'ABOUT','about.title':'One table,<br>one big home.','about.desc':'Қарақалпағым serves national dishes in a clean, modern format. Menu names and prices are taken from the original menu you provided.','menu.tag':'MENU · DASTURXAN','menu.title':'Pick your favorite.','menu.desc':'Like TopStop: individual cards with a dish photo, its name and the price from the original menu.','menu.search':'Search dishes…','story.title':'Service charge','story.desc':'As shown on the original menu, a 10% service charge applies.','contact.tag':'CONTACT','contact.title':'Come as a guest.<br>The table is ready.','contact.hours':'Every day · 10:00 — 23:00','reserve.tag':'RESERVATION','reserve.title':'Reserve a table','reserve.name':'Your name','reserve.phone':'Phone','reserve.guests':'Number of guests','reserve.send':'Send request','all':'All','searchNone':'Nothing found'},
 uz:{'nav.menu':'Menyu','nav.about':'Biz haqimizda','nav.contacts':'Aloqa','nav.reserve':'Stol bron qilish','hero.line1':'Ta’m. An’ana.','hero.line2':'Uydek iliq.','hero.desc':'Nukus markazidagi milliy dasturxon: tanish ta’mlar, mo‘l porsiyalar va uydek muhit.','hero.open':'Menyuni ochish','hero.more':'Biz haqimizda','hero.note':'Har kuni · 10:00 — 23:00','about.tag':'RESTORAN HAQIDA','about.title':'Bir dasturxon,<br>bir katta uy.','about.desc':'Қарақалпағым milliy taomlarni qulay va zamonaviy formatda taqdim etadi. Menyudagi nomlar va narxlar siz yuborgan asl menyudan olingan.','menu.tag':'MENYU · DASTURXAN','menu.title':'Yoqganini tanlang.','menu.desc':'TopStop uslubida: taom rasmi, nomi va asl menyudagi narxi bitta kartada.','menu.search':'Taom qidirish…','story.title':'Xizmat haqi','story.desc':'Asl menyuda ko‘rsatilganidek, xizmat haqi 10%.','contact.tag':'ALOQA','contact.title':'Mehmon bo‘ling.<br>Dasturxon tayyor.','contact.hours':'Har kuni · 10:00 — 23:00','reserve.tag':'BRON','reserve.title':'Stol bron qilish','reserve.name':'Ismingiz','reserve.phone':'Telefon','reserve.guests':'Mehmonlar soni','reserve.send':'So‘rov yuborish','all':'Barchasi','searchNone':'Hech narsa topilmadi'}
};
function t(key){return (translations[state.lang]&&translations[state.lang][key])||translations.ru[key]||key}
function applyLang(){document.documentElement.lang=state.lang==='kaa'?'kaa':state.lang; $$('[data-i18n]').forEach(el=>el.innerHTML=t(el.dataset.i18n)); $$('[data-i18n-placeholder]').forEach(el=>el.placeholder=t(el.dataset.i18nPlaceholder)); $$('.lang').forEach(b=>b.classList.toggle('active',b.dataset.lang===state.lang)); document.title='Қарақалпағым — '+(state.lang==='en'?'national cuisine':state.lang==='uz'?'milliy taomlar':state.lang==='ru'?'национальная кухня':'ұлттық асхана'); renderCats(); render();}
function renderCats(){const cats=[...new Set(MENU_ITEMS.map(i=>i.category))]; $('#cats').innerHTML=[`<button class="cat ${state.cat==='all'?'active':''}" data-cat="all">${t('all')}</button>`].concat(cats.map(c=>`<button class="cat ${state.cat===c?'active':''}" data-cat="${c}">${c}</button>`)).join(''); $$('#cats .cat').forEach(b=>b.onclick=()=>{state.cat=b.dataset.cat;renderCats();render()})}
function card(item){return `<article class="card"><div class="card-photo"><img src="${item.image}" alt="${item.name}" loading="lazy"></div><div class="card-body"><div class="card-meta"><span class="card-cat">${item.category}</span><span class="price">${item.price} сум</span></div><h3>${item.name}</h3><div class="card-foot"><button class="tiny" onclick="quickReserve('${item.name.replace(/'/g,"\\'")}')">${state.lang==='en'?'Reserve':state.lang==='uz'?'Bron':state.lang==='ru'?'Выбрать':'Таңдау'}</button></div></div></article>`}
function render(){const q=($('#search').value||'').trim().toLowerCase(); let data=MENU_ITEMS.filter(i=>(state.cat==='all'||i.category===state.cat)&&(!q||i.name.toLowerCase().includes(q)||i.category.toLowerCase().includes(q))); $('#grid').innerHTML=data.length?data.map(card).join(''):`<div class="empty">${t('searchNone')}</div>`}
$('#search').addEventListener('input',render); $('.lang-switch').addEventListener('click',e=>{const b=e.target.closest('.lang');if(!b)return;state.lang=b.dataset.lang;localStorage.setItem('qaraqalpagim-lang',state.lang);applyLang()});
$('#menuBtn').onclick=()=>$('#drawer').classList.add('open'); $('#reserveBtn').onclick=$('#reserveContact').onclick=$('#drawerReserve').onclick=()=>$('#reserveModal').classList.add('open'); $('#sendReserve').onclick=()=>{closeAll();toast(state.lang==='en'?'Request sent — we will contact you.':state.lang==='uz'?'So‘rov yuborildi — siz bilan bog‘lanamiz.':state.lang==='ru'?'Заявка отправлена — мы свяжемся с вами.':'Өтінім жіберілді — сізбен хабарласамыз.' )}; $$('[data-close]').forEach(x=>x.onclick=closeAll); function closeAll(){$$('.modal,.drawer').forEach(x=>x.classList.remove('open'))} function toast(v){const e=$('#toast');e.textContent=v;e.classList.add('show');setTimeout(()=>e.classList.remove('show'),2200)} function quickReserve(name){$('#reserveModal').classList.add('open');$('.small h3').dataset.item=name}
window.quickReserve=quickReserve;applyLang();
