const $=s=>document.querySelector(s), $$=s=>document.querySelectorAll(s);
const state={lang:localStorage.getItem('qaraqalpagim-lang')||'kaa',cat:'all',cart:[]};
const translations={
 kaa:{'nav.menu':'Menyu','nav.about':'Biz haqqında','nav.contacts':'Kontaktlarımız','nav.delivery':'Jetkerip beriwge buyırtpa beriw','nav.reserve':'stolın bántlew','hero.line1':'Dámi. Dástúr.','hero.line2':'Úydegidey jıllılıq.','hero.desc':'Nókistiń qaq ortasındaǵı milliy dasturxan: tanıs dámler, úlken porciyalar hám úy keypiyatı.','hero.open':'Menyudi ashiw','hero.more':'Biz haqqında','hero.note':'Hár kúni · 10:00 - 23:00','about.tag':'RESTORAN HAQQINDA','about.title':'Bir dasturxan, bir úlken úy.','about.desc':'Qaraqalpaqımda milliy taǵamlar qolaylı zamanagóy formatta tartıladı. Menyudegi atamalar hám bahalar berilgen tiykarģı menyuden alıngan.','menu.tag':'MENYU MENU','menu.title':'Mazalısın tańlań.','menu.desc':'TopStoptaǵı sıyaqlı: súwret, atama hám original menyudiń bahası kórsetilgen bólek kartochkalar.','menu.search':'Taǵam izlenip atır...','story.title':'Xizmet haqi','story.desc':'Dáslepki menyude kórsetilgenindey, servis jıyımı 10% ti quraydı.','contact.tag':'KONTAKTLAR','contact.title':'Quwanıshlı bolamız. Dasturxan tayar.','contact.hours':'Hár kúni · 10:00 - 23:00','reserve.tag':'Restoran haqqında','reserve.title':'stolın bántlew','reserve.desc':'Bul kafege kelip, aldınnan stol ielewdi qálegen miymanlar ushın óz aldına arza bolıp esaplanadı.','reserve.name':'Sizin atınız','reserve.phone':'Telefon','reserve.guests':'Qonaqlar sanı','reserve.send':'Arza jiberiw','delivery.tag':'JETKERIP BERIW','delivery.title':'Úyge awqat buyırtıw','delivery.desc':'Taǵamlardı tańlań, mánzildi kórsetiń - biz buyırtpanı jetkerip beriw ushın siz benen baylanısamız.','delivery.total':'Jámi','delivery.name':'Sizin atınız','delivery.phone':'Telefon','delivery.address':'Jetkerip beriw adresi','delivery.send':'Buyırtpa jiberiw','delivery.empty':'Házirshe hesh nárse tańlanbaǵan.','delivery.added':'Buyırtpaǵa qosıldı','delivery.success':'Buyırtpa qabıl etildi - siz benen baylanısamız.','all':'Hámmesi','searchNone':'Hesh nárse tabılmadı','cart.add':'Buyırtpa boyınsha','cart.remove':'Óshiriw'},
 ru:{'nav.menu':'Меню','nav.about':'О нас','nav.contacts':'Контакты','nav.delivery':'Заказать доставку','nav.reserve':'Забронировать стол','hero.line1':'Вкус. Традиция.','hero.line2':'Тепло как дома.','hero.desc':'Национальный дастархан в самом сердце Нукуса: знакомые вкусы, большие порции и домашняя атмосфера.','hero.open':'Открыть меню','hero.more':'О нас','hero.note':'Ежедневно · 10:00 — 23:00','about.tag':'О РЕСТОРАНЕ','about.title':'Один дастархан,<br>один большой дом.','about.desc':'В Қарақалпағым национальные блюда подаются в удобном современном формате. Названия и цены в меню взяты из предоставленного оригинального меню.','menu.tag':'МЕНЮ · MENU','menu.title':'Выбирайте вкусное.','menu.desc':'Как в TopStop: отдельные карточки с фото, названием и ценой из оригинального меню.','menu.search':'Поиск блюда…','story.title':'Сервисный сбор','story.desc':'Как указано в оригинальном меню, сервисный сбор составляет 10%.','contact.tag':'КОНТАКТЫ','contact.title':'Будем рады.<br>Дастархан готов.','contact.hours':'Ежедневно · 10:00 — 23:00','reserve.tag':'БРОНЬ СТОЛА','reserve.title':'Забронировать стол','reserve.desc':'Это отдельная заявка для гостей, которые придут в кафе и хотят заранее занять столик.','reserve.name':'Ваше имя','reserve.phone':'Телефон','reserve.guests':'Количество гостей','reserve.send':'Отправить заявку','delivery.tag':'ДОСТАВКА','delivery.title':'Заказать еду домой','delivery.desc':'Выберите блюда, укажите адрес — мы свяжемся с вами для доставки заказа.','delivery.total':'Итого','delivery.name':'Ваше имя','delivery.phone':'Телефон','delivery.address':'Адрес доставки','delivery.send':'Отправить заказ','delivery.empty':'Пока ничего не выбрано.','delivery.added':'Добавлено в заказ','delivery.success':'Заказ принят — мы свяжемся с вами.','all':'Все','searchNone':'Ничего не найдено','cart.add':'В заказ','cart.remove':'Удалить'},
 en:{'nav.menu':'Menu','nav.about':'About','nav.contacts':'Contacts','nav.delivery':'Order delivery','nav.reserve':'Reserve a table','hero.line1':'Taste. Tradition.','hero.line2':'Warm as home.','hero.desc':'A national table in the heart of Nukus: familiar flavors, generous portions and a welcoming atmosphere.','hero.open':'Open menu','hero.more':'About us','hero.note':'Every day · 10:00 — 23:00','about.tag':'ABOUT','about.title':'One table,<br>one big home.','about.desc':'Қарақалпағым serves national dishes in a clean, modern format. Menu names and prices are taken from the original menu you provided.','menu.tag':'MENU · DASTURXAN','menu.title':'Pick your favorite.','menu.desc':'Like TopStop: individual cards with a dish photo, its name and the price from the original menu.','menu.search':'Search dishes…','story.title':'Service charge','story.desc':'As shown on the original menu, a 10% service charge applies.','contact.tag':'CONTACT','contact.title':'Come as a guest.<br>The table is ready.','contact.hours':'Every day · 10:00 — 23:00','reserve.tag':'TABLE RESERVATION','reserve.title':'Reserve a table','reserve.desc':'This is for guests who will come to the café and want a table reserved in advance.','reserve.name':'Your name','reserve.phone':'Phone','reserve.guests':'Number of guests','reserve.send':'Send request','delivery.tag':'DELIVERY','delivery.title':'Order food for delivery','delivery.desc':'Choose your dishes and enter your address — we will contact you about delivering the order.','delivery.total':'Total','delivery.name':'Your name','delivery.phone':'Phone','delivery.address':'Delivery address','delivery.send':'Send order','delivery.empty':'No dishes selected yet.','delivery.added':'Added to order','delivery.success':'Order received — we will contact you.','all':'All','searchNone':'Nothing found','cart.add':'Add to order','cart.remove':'Remove'},
 uz:{'nav.menu':'Menyu','nav.about':'Biz haqimizda','nav.contacts':'Aloqa','nav.delivery':'Yetkazib berishga buyurtma','nav.reserve':'Stol bron qilish','hero.line1':'Ta’m. An’ana.','hero.line2':'Uydek iliq.','hero.desc':'Nukus markazidagi milliy dasturxon: tanish ta’mlar, mo‘l porsiyalar va uydek muhit.','hero.open':'Menyuni ochish','hero.more':'Biz haqimizda','hero.note':'Har kuni · 10:00 — 23:00','about.tag':'RESTORAN HAQIDA','about.title':'Bir dasturxon,<br>bir katta uy.','about.desc':'Қарақалпағым milliy taomlarni qulay va zamonaviy formatda taqdim etadi. Menyudagi nomlar va narxlar siz yuborgan asl menyudan olingan.','menu.tag':'MENYU · DASTURXAN','menu.title':'Yoqganini tanlang.','menu.desc':'TopStop uslubida: taom rasmi, nomi va asl menyudagi narxi bitta kartada.','menu.search':'Taom qidirish…','story.title':'Xizmat haqi','story.desc':'Asl menyuda ko‘rsatilganidek, xizmat haqi 10%.','contact.tag':'ALOQA','contact.title':'Mehmon bo‘ling.<br>Dasturxon tayyor.','contact.hours':'Har kuni · 10:00 — 23:00','reserve.tag':'STOL BRONI','reserve.title':'Stol bron qilish','reserve.desc':'Bu kafega keladigan mehmonlar uchun stolni oldindan band qilish so‘rovi.','reserve.name':'Ismingiz','reserve.phone':'Telefon','reserve.guests':'Mehmonlar soni','reserve.send':'So‘rov yuborish','delivery.tag':'YETKAZIB BERISH','delivery.title':'Uyga ovqat buyurtma qilish','delivery.desc':'Taomlarni tanlang, manzilingizni yozing — buyurtmani yetkazib berish uchun siz bilan bog‘lanamiz.','delivery.total':'Jami','delivery.name':'Ismingiz','delivery.phone':'Telefon','delivery.address':'Yetkazib berish manzili','delivery.send':'Buyurtmani yuborish','delivery.empty':'Hali taom tanlanmagan.','delivery.added':'Buyurtmaga qo‘shildi','delivery.success':'Buyurtma qabul qilindi — siz bilan bog‘lanamiz.','all':'Barchasi','searchNone':'Hech narsa topilmadi','cart.add':'Buyurtmaga qo‘shish','cart.remove':'O‘chirish'}
};
function t(key){return (translations[state.lang]&&translations[state.lang][key])||translations.ru[key]||key}
function applyLang(){document.documentElement.lang=state.lang==='kaa'?'kaa':state.lang;$$('[data-i18n]').forEach(el=>el.innerHTML=t(el.dataset.i18n));$$('[data-i18n-placeholder]').forEach(el=>el.placeholder=t(el.dataset.i18nPlaceholder));$$('.lang').forEach(b=>b.classList.toggle('active',b.dataset.lang===state.lang));document.title='Қарақалпағым — '+(state.lang==='en'?'national cuisine':state.lang==='uz'?'milliy taomlar':state.lang==='ru'?'национальная кухня':'ұлттық асхана');renderCats();renderCart();render();updateDeliveryCount()}
function renderCats(){const cats=[...new Set(MENU_ITEMS.map(i=>i.category))];$('#cats').innerHTML=[`<button class="cat ${state.cat==='all'?'active':''}" data-cat="all">${t('all')}</button>`].concat(cats.map(c=>`<button class="cat ${state.cat===c?'active':''}" data-cat="${c}">${c}</button>`)).join('');$$('#cats .cat').forEach(b=>b.onclick=()=>{state.cat=b.dataset.cat;renderCats();render()})}
function money(n){return n.toLocaleString('ru-RU')+' сум'}
function card(item){return `<article class="card"><div class="card-photo"><img src="${item.image}" alt="${item.name}" loading="lazy"></div><div class="card-body"><div class="card-meta"><span class="card-cat">${item.category}</span><span class="price">${item.price} сум</span></div><h3>${item.name}</h3><div class="card-foot"><button class="tiny" onclick="addToCart(${item.id})">${t('cart.add')}</button></div></div></article>`}
function render(){const q=($('#search').value||'').trim().toLowerCase();let data=MENU_ITEMS.filter(i=>(state.cat==='all'||i.category===state.cat)&&(!q||i.name.toLowerCase().includes(q)||i.category.toLowerCase().includes(q)));$('#grid').innerHTML=data.length?data.map(card).join(''):`<div class="empty">${t('searchNone')}</div>`}
function addToCart(id){const item=MENU_ITEMS.find(x=>x.id===id);if(!item)return;const existing=state.cart.find(x=>x.id===id);existing?existing.qty++:state.cart.push({id,qty:1});renderCart();updateDeliveryCount();toast(t('delivery.added'))}
function removeFromCart(id){const existing=state.cart.find(x=>x.id===id);if(!existing)return;existing.qty--;if(existing.qty<=0)state.cart=state.cart.filter(x=>x.id!==id);renderCart();updateDeliveryCount()}
function renderCart(){const box=$('#cartItems');if(!box)return;if(!state.cart.length){box.innerHTML=`<div class="cart-empty">${t('delivery.empty')}</div>`;$('#cartTotal').textContent='0 сум';return}let total=0;box.innerHTML=state.cart.map(row=>{const item=MENU_ITEMS.find(x=>x.id===row.id);const price=Number(item.price.replace(/\s/g,''));total+=price*row.qty;return `<div class="cart-row"><div><strong>${item.name}</strong><span>${item.price} сум × ${row.qty}</span></div><div class="cart-controls"><button onclick="removeFromCart(${item.id})">−</button><span>${row.qty}</span><button onclick="addToCart(${item.id})">+</button></div></div>`}).join('');$('#cartTotal').textContent=money(total)}
function updateDeliveryCount(){const btns=[$('#deliveryBtn'),$('#heroDelivery'),$('#contactDelivery'),$('#drawerDelivery')];const count=state.cart.reduce((a,b)=>a+b.qty,0);btns.forEach(b=>{if(b)b.dataset.count=count||''})}
function openDelivery(){renderCart();$('#deliveryModal').classList.add('open')}
function openReserve(){$('#reserveModal').classList.add('open')}
$('#search').addEventListener('input',render);$('.lang-switch').addEventListener('click',e=>{const b=e.target.closest('.lang');if(!b)return;state.lang=b.dataset.lang;localStorage.setItem('qaraqalpagim-lang',state.lang);applyLang()});
$('#menuBtn').onclick=()=>$('#drawer').classList.add('open');
$('#reserveBtn').onclick=$('#reserveContact').onclick=$('#drawerReserve').onclick=$('#heroReserve').onclick=openReserve;
$('#deliveryBtn').onclick=$('#contactDelivery').onclick=$('#drawerDelivery').onclick=$('#heroDelivery').onclick=openDelivery;
$('#sendReserve').onclick=()=>{closeAll();toast(state.lang==='en'?'Reservation request sent.':state.lang==='uz'?'Stol bron qilish so‘rovi yuborildi.':state.lang==='ru'?'Заявка на бронирование стола отправлена.':'Үстел броньлаў өтинми жиберилди.' )};
$('#sendDelivery').onclick=()=>{if(!state.cart.length){toast(t('delivery.empty'));return}closeAll();state.cart=[];renderCart();updateDeliveryCount();toast(t('delivery.success'))};
$$('[data-close]').forEach(x=>x.onclick=closeAll);function closeAll(){$$('.modal,.drawer').forEach(x=>x.classList.remove('open'))}function toast(v){const e=$('#toast');e.textContent=v;e.classList.add('show');setTimeout(()=>e.classList.remove('show'),2200)}
window.addToCart=addToCart;window.removeFromCart=removeFromCart;applyLang();
